create table Author(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE,
    password varchar NOT NULL
);
create table Task(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    content varchar(255) NOT NULL,
    user_id int,
    constraint fk_author foreign key(user_id) references Author(id)
);
create table Authorities
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  int,
    authority varchar(50),
    foreign key (user_id) references Author(id)
);
insert into author(name, password)
values('admin', '$2a$10$EjF87obHuOauQA2FbjwX9er37/otglPbPPo6oT0UQ9V.Xzb5Xqcse');
insert into authorities(user_id, authority)
values (1,'ROLE_ADMIN');