create table Author(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    password varchar NOT NULL
);
create table Task(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    content varchar NOT NULL,
    user_id int,
    constraint fk_author foreign key(user_id) references Author(id)
);


INSERT INTO Author (name,password) VALUES ('first author', 'password1');
INSERT INTO Author (name,password) VALUES ('second author', 'password2');
INSERT INTO Task (title,content,user_id) VALUES('task1', 'task for author 1',1);
INSERT INTO Task (title,content,user_id) VALUES('task2', 'task for author 1',1);
INSERT INTO Task (title,content,user_id) VALUES('task1', 'task for author 2',2);
INSERT INTO Task (title,content,user_id) VALUES('task2', 'task for author 2',2);