create table Author(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL
);
create table Task(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title varchar NOT NULL UNIQUE,
                     content varchar NOT NULL,
                     user_id int,
                     constraint fk_author foreign key(user_id) references Author(id)
)